### ISSUE TITLE
请问maotu要怎么集成到vue2前端中呢？还有这个系统为什么使用菜单管理生成新的目录，会出现404的现象了，确保新的路径在前端中存在

### ISSUE THREAD

**Issue by zmdcs** [yaolunmao/maotu-ry#1]
![image](https://github.com/yaolunmao/maotu-ry/assets/40875421/6df79aac-7e76-45dd-ac7f-73c2cf849d61)

**Comment by yaolunmao** [comment]
vue2使用的话只能是微前端或者iframe，vue2项目作为主应用，vue3项目引入maotu作为子应用，至于您说的新目录404的问题可以看下若依的相关文档哈，我只是用若依框架作为演示项目，并没有改若依的代码
