### ISSUE TITLE
请问预览的时候如何关闭悬浮显示图元属性的框呢？

### ISSUE THREAD

**Issue by zmdcs** [yaolunmao/maotu-ry#3]
![image](https://github.com/yaolunmao/maotu-ry/assets/40875421/4fddfe94-38eb-4f14-86de-5345f1d62ede)
属性信息的框

**Comment by yaolunmao** [comment]
showPopover传false 参考http://mt.yaolm.top/guide/attr-event/mt-preview.html

**Comment by zmdcs** [comment]
谢谢大佬





------------------ 原始邮件 ------------------
发件人: 咬轮猫 ***@***.***&gt;
发送时间: 2024年5月10日 12:07
收件人: yaolunmao/maotu-ry ***@***.***&gt;
抄送: zmdcs ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yaolunmao/maotu-ry] 请问预览的时候如何关闭悬浮显示图元属性的框呢？ (Issue #3)





 
showPopover传false 参考http://mt.yaolm.top/guide/attr-event/mt-preview.html

**Comment by zmdcs** [comment]
![image](https://github.com/yaolunmao/maotu-ry/assets/40875421/e2397f31-3397-4750-b1ea-cbdbb92a3742)
不好意思，不是这么写吗？悬浮框还是有

**Comment by yaolunmao** [comment]
你这么写传的是字符串，正确的写法是:showPopover="false"，然后插件版本需要升级到0.3.3
&nbsp;


Circle
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月10日(星期五) 下午2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yaolunmao/maotu-ry] 请问预览的时候如何关闭悬浮显示图元属性的框呢？ (Issue #3)














 
image.png (view on web)
 不好意思，不是这么写吗？悬浮框还是有
