### ISSUE TITLE
请问大佬你知道如果我想要在未登录的情况下直接访问webtopoPreview要怎么操作吗？

### ISSUE THREAD

**Issue by zmdcs** [yaolunmao/maotu-ry#4]
我看到preview中的websocket操作需要token，有没有办法在不登录的情况下直接访问webtopoPreview界面，然后直接按照默认的用户名密码自动执行登录操作获取token呢？

**Comment by zmdcs** [comment]
目前我在白名单中加入/webtopoPreview可以免除被拦截，但是未被拦截也会显示页面是404，我在route.js中有加
![image](https://github.com/yaolunmao/maotu-ry/assets/40875421/387686ff-39af-481c-9cfe-da9f8197124f)
zheyang这样的路径

**Comment by yaolunmao** [comment]
前端路由把预览页的路由加到白名单，后端把请求拦截器那里的验证去了就行

**Comment by zmdcs** [comment]
谢谢
